/* Generated by the Cratylus to C compiler */

/* Compile with -lgmp */

#include <stdio.h>
#include <gmp.h>

#define CONSTANTS 2
mpz_t c[CONSTANTS];
#define VARS 39
mpz_t v[VARS];

char *n[] = {
	"Z", "a", "b", "c", "e", "d", "g", "f", "i", "h", "k", "j", "m", "l", "A", "B",
	"o", "n", "q", "p", "s", "r", "u", "t", "w", "v", "y", "x", "z", "C", "E", "D",
	"G", "F", "I", "H", "K", "J", "L",
};

int main()
{
	int i, z;

	/* Initialize constants */
	mpz_init_set_str(c[0], "1", 10);
	mpz_init_set_str(c[1], "5", 10);

	/* Initialize variables */
	for (i = 0; i < VARS; i++) {
		mpz_init(v[i]);
	}

	/* Goal: ? a^5H */
	mpz_add(v[1], v[1], c[1]);
	mpz_add(v[35], v[35], c[0]);

	while (1) {
		if (0) {
		} else if (mpz_cmp(v[35], c[0]) >= 0) {
			/* H => mZ */
			mpz_sub(v[35], v[35], c[0]);
			mpz_add(v[12], v[12], c[0]);
			mpz_add(v[0], v[0], c[0]);
		} else if (mpz_cmp(v[1], c[0]) >= 0 && mpz_cmp(v[12], c[0]) >= 0) {
			/* am => af */
			mpz_sub(v[1], v[1], c[0]);
			mpz_sub(v[12], v[12], c[0]);
			mpz_add(v[1], v[1], c[0]);
			mpz_add(v[7], v[7], c[0]);
		} else if (mpz_cmp(v[12], c[0]) >= 0) {
			/* m => J */
			mpz_sub(v[12], v[12], c[0]);
			mpz_add(v[37], v[37], c[0]);
		} else if (mpz_cmp(v[1], c[0]) >= 0 && mpz_cmp(v[7], c[0]) >= 0) {
			/* af => aB */
			mpz_sub(v[1], v[1], c[0]);
			mpz_sub(v[7], v[7], c[0]);
			mpz_add(v[1], v[1], c[0]);
			mpz_add(v[15], v[15], c[0]);
		} else if (mpz_cmp(v[7], c[0]) >= 0) {
			/* f => k */
			mpz_sub(v[7], v[7], c[0]);
			mpz_add(v[10], v[10], c[0]);
		} else if (mpz_cmp(v[1], c[0]) >= 0 && mpz_cmp(v[15], c[0]) >= 0) {
			/* aB => u */
			mpz_sub(v[1], v[1], c[0]);
			mpz_sub(v[15], v[15], c[0]);
			mpz_add(v[22], v[22], c[0]);
		} else if (mpz_cmp(v[15], c[0]) >= 0) {
			/* B => u */
			mpz_sub(v[15], v[15], c[0]);
			mpz_add(v[22], v[22], c[0]);
		} else if (mpz_cmp(v[22], c[0]) >= 0) {
			/* u => cL */
			mpz_sub(v[22], v[22], c[0]);
			mpz_add(v[3], v[3], c[0]);
			mpz_add(v[38], v[38], c[0]);
		} else if (mpz_cmp(v[38], c[0]) >= 0) {
			/* L => eG */
			mpz_sub(v[38], v[38], c[0]);
			mpz_add(v[4], v[4], c[0]);
			mpz_add(v[32], v[32], c[0]);
		} else if (mpz_cmp(v[32], c[0]) >= 0) {
			/* G => f */
			mpz_sub(v[32], v[32], c[0]);
			mpz_add(v[7], v[7], c[0]);
		} else if (mpz_cmp(v[3], c[0]) >= 0 && mpz_cmp(v[10], c[0]) >= 0) {
			/* ck => cr */
			mpz_sub(v[3], v[3], c[0]);
			mpz_sub(v[10], v[10], c[0]);
			mpz_add(v[3], v[3], c[0]);
			mpz_add(v[21], v[21], c[0]);
		} else if (mpz_cmp(v[10], c[0]) >= 0) {
			/* k => d */
			mpz_sub(v[10], v[10], c[0]);
			mpz_add(v[5], v[5], c[0]);
		} else if (mpz_cmp(v[3], c[0]) >= 0 && mpz_cmp(v[21], c[0]) >= 0) {
			/* cr => b */
			mpz_sub(v[3], v[3], c[0]);
			mpz_sub(v[21], v[21], c[0]);
			mpz_add(v[2], v[2], c[0]);
		} else if (mpz_cmp(v[21], c[0]) >= 0) {
			/* r => b */
			mpz_sub(v[21], v[21], c[0]);
			mpz_add(v[2], v[2], c[0]);
		} else if (mpz_cmp(v[2], c[0]) >= 0 && mpz_cmp(v[0], c[0]) >= 0) {
			/* bZ => yZ */
			mpz_sub(v[2], v[2], c[0]);
			mpz_sub(v[0], v[0], c[0]);
			mpz_add(v[26], v[26], c[0]);
			mpz_add(v[0], v[0], c[0]);
		} else if (mpz_cmp(v[2], c[0]) >= 0) {
			/* b => j */
			mpz_sub(v[2], v[2], c[0]);
			mpz_add(v[11], v[11], c[0]);
		} else if (mpz_cmp(v[26], c[0]) >= 0 && mpz_cmp(v[0], c[0]) >= 0) {
			/* yZ => t */
			mpz_sub(v[26], v[26], c[0]);
			mpz_sub(v[0], v[0], c[0]);
			mpz_add(v[23], v[23], c[0]);
		} else if (mpz_cmp(v[26], c[0]) >= 0) {
			/* y => t */
			mpz_sub(v[26], v[26], c[0]);
			mpz_add(v[23], v[23], c[0]);
		} else if (mpz_cmp(v[23], c[0]) >= 0) {
			/* t => iK */
			mpz_sub(v[23], v[23], c[0]);
			mpz_add(v[8], v[8], c[0]);
			mpz_add(v[36], v[36], c[0]);
		} else if (mpz_cmp(v[36], c[0]) >= 0) {
			/* K => lE */
			mpz_sub(v[36], v[36], c[0]);
			mpz_add(v[13], v[13], c[0]);
			mpz_add(v[30], v[30], c[0]);
		} else if (mpz_cmp(v[30], c[0]) >= 0) {
			/* E => b */
			mpz_sub(v[30], v[30], c[0]);
			mpz_add(v[2], v[2], c[0]);
		} else if (mpz_cmp(v[8], c[0]) >= 0 && mpz_cmp(v[11], c[0]) >= 0) {
			/* ij => is */
			mpz_sub(v[8], v[8], c[0]);
			mpz_sub(v[11], v[11], c[0]);
			mpz_add(v[8], v[8], c[0]);
			mpz_add(v[20], v[20], c[0]);
		} else if (mpz_cmp(v[11], c[0]) >= 0) {
			/* j => I */
			mpz_sub(v[11], v[11], c[0]);
			mpz_add(v[34], v[34], c[0]);
		} else if (mpz_cmp(v[8], c[0]) >= 0 && mpz_cmp(v[20], c[0]) >= 0) {
			/* is => x */
			mpz_sub(v[8], v[8], c[0]);
			mpz_sub(v[20], v[20], c[0]);
			mpz_add(v[27], v[27], c[0]);
		} else if (mpz_cmp(v[20], c[0]) >= 0) {
			/* s => x */
			mpz_sub(v[20], v[20], c[0]);
			mpz_add(v[27], v[27], c[0]);
		} else if (mpz_cmp(v[27], c[0]) >= 0) {
			/* x => DZ */
			mpz_sub(v[27], v[27], c[0]);
			mpz_add(v[31], v[31], c[0]);
			mpz_add(v[0], v[0], c[0]);
		} else if (mpz_cmp(v[31], c[0]) >= 0) {
			/* D => j */
			mpz_sub(v[31], v[31], c[0]);
			mpz_add(v[11], v[11], c[0]);
		} else if (mpz_cmp(v[34], c[0]) >= 0) {
			/* I => k */
			mpz_sub(v[34], v[34], c[0]);
			mpz_add(v[10], v[10], c[0]);
		} else if (mpz_cmp(v[5], c[0]) >= 0 && mpz_cmp(v[0], c[0]) >= 0) {
			/* dZ => wZ */
			mpz_sub(v[5], v[5], c[0]);
			mpz_sub(v[0], v[0], c[0]);
			mpz_add(v[24], v[24], c[0]);
			mpz_add(v[0], v[0], c[0]);
		} else if (mpz_cmp(v[5], c[0]) >= 0) {
			/* d => h */
			mpz_sub(v[5], v[5], c[0]);
			mpz_add(v[9], v[9], c[0]);
		} else if (mpz_cmp(v[24], c[0]) >= 0 && mpz_cmp(v[0], c[0]) >= 0) {
			/* wZ => o */
			mpz_sub(v[24], v[24], c[0]);
			mpz_sub(v[0], v[0], c[0]);
			mpz_add(v[16], v[16], c[0]);
		} else if (mpz_cmp(v[24], c[0]) >= 0) {
			/* w => o */
			mpz_sub(v[24], v[24], c[0]);
			mpz_add(v[16], v[16], c[0]);
		} else if (mpz_cmp(v[16], c[0]) >= 0) {
			/* o => d */
			mpz_sub(v[16], v[16], c[0]);
			mpz_add(v[5], v[5], c[0]);
		} else if (mpz_cmp(v[9], c[0]) >= 0 && mpz_cmp(v[13], c[0]) >= 0) {
			/* hl => lp */
			mpz_sub(v[9], v[9], c[0]);
			mpz_sub(v[13], v[13], c[0]);
			mpz_add(v[13], v[13], c[0]);
			mpz_add(v[19], v[19], c[0]);
		} else if (mpz_cmp(v[9], c[0]) >= 0) {
			/* h => g */
			mpz_sub(v[9], v[9], c[0]);
			mpz_add(v[6], v[6], c[0]);
		} else if (mpz_cmp(v[13], c[0]) >= 0 && mpz_cmp(v[19], c[0]) >= 0) {
			/* lp => v */
			mpz_sub(v[13], v[13], c[0]);
			mpz_sub(v[19], v[19], c[0]);
			mpz_add(v[25], v[25], c[0]);
		} else if (mpz_cmp(v[19], c[0]) >= 0) {
			/* p => v */
			mpz_sub(v[19], v[19], c[0]);
			mpz_add(v[25], v[25], c[0]);
		} else if (mpz_cmp(v[25], c[0]) >= 0) {
			/* v => CZ */
			mpz_sub(v[25], v[25], c[0]);
			mpz_add(v[29], v[29], c[0]);
			mpz_add(v[0], v[0], c[0]);
		} else if (mpz_cmp(v[29], c[0]) >= 0) {
			/* C => h */
			mpz_sub(v[29], v[29], c[0]);
			mpz_add(v[9], v[9], c[0]);
		} else if (mpz_cmp(v[4], c[0]) >= 0 && mpz_cmp(v[6], c[0]) >= 0) {
			/* eg => en */
			mpz_sub(v[4], v[4], c[0]);
			mpz_sub(v[6], v[6], c[0]);
			mpz_add(v[4], v[4], c[0]);
			mpz_add(v[17], v[17], c[0]);
		} else if (mpz_cmp(v[6], c[0]) >= 0) {
			/* g => q */
			mpz_sub(v[6], v[6], c[0]);
			mpz_add(v[18], v[18], c[0]);
		} else if (mpz_cmp(v[4], c[0]) >= 0 && mpz_cmp(v[17], c[0]) >= 0) {
			/* en => z */
			mpz_sub(v[4], v[4], c[0]);
			mpz_sub(v[17], v[17], c[0]);
			mpz_add(v[28], v[28], c[0]);
		} else if (mpz_cmp(v[17], c[0]) >= 0) {
			/* n => z */
			mpz_sub(v[17], v[17], c[0]);
			mpz_add(v[28], v[28], c[0]);
		} else if (mpz_cmp(v[28], c[0]) >= 0) {
			/* z => aF */
			mpz_sub(v[28], v[28], c[0]);
			mpz_add(v[1], v[1], c[0]);
			mpz_add(v[33], v[33], c[0]);
		} else if (mpz_cmp(v[33], c[0]) >= 0) {
			/* F => g */
			mpz_sub(v[33], v[33], c[0]);
			mpz_add(v[6], v[6], c[0]);
		} else if (mpz_cmp(v[1], c[0]) >= 0 && mpz_cmp(v[18], c[0]) >= 0) {
			/* aq => A */
			mpz_sub(v[1], v[1], c[0]);
			mpz_sub(v[18], v[18], c[0]);
			mpz_add(v[14], v[14], c[0]);
		} else if (mpz_cmp(v[18], c[0]) >= 0) {
			/* q => A */
			mpz_sub(v[18], v[18], c[0]);
			mpz_add(v[14], v[14], c[0]);
		} else if (mpz_cmp(v[14], c[0]) >= 0) {
			/* A => m */
			mpz_sub(v[14], v[14], c[0]);
			mpz_add(v[12], v[12], c[0]);
		} else if (mpz_cmp(v[37], c[0]) >= 0) {
			/* J */
			mpz_sub(v[37], v[37], c[0]);
		} else {
			break;
		}
	}

	z = 1;
	for (i = 0; i < VARS; i++) {
		if (mpz_cmp_ui(v[i], 0) > 0) {
			if (!z) {
				printf(" ");
			}
			z = 0;
			printf("%s", n[i]);
			if (mpz_cmp_ui(v[i], 1) > 0) {
				printf("^");
				mpz_out_str(stdout, 10, v[i]);
			}
		}
	}
	if (z) {
		printf("1");
	}
	printf("\n");

	return 0;
}
